### ISSUE TITLE
Widget to toggle last used tunnel

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/viscerion#101]
Functional equivalent of the Quick Settings tile, would be
a good way to try my hands on the remote views API as well.

**Comment by MSF-Jarvis** [comment]
The use-case for this is pretty slim since the QS tile already exists and not many people want this anyway, lmk here if you're part of those who do.

**Comment by msfjarvis** [comment]
Got a couple of Play Store reviews asking for this

**Comment by msfjarvis** [comment]
I just can't, this entire API surface makes me want to kill myself.
