### ISSUE TITLE
[BUG] Hostnames should resolve to their IPs while saving

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/viscerion#151]
**Describe the bug**

Apparently sometime between v4.0.0 and v5.1.1, DNS names have started being enforced as numeric. I'm trying to confirm this as well as compare behaviour with the official client atm.

**To Reproduce**
1. Go to the editing mode for any tunnel
2. Try changing Interface DNS to `one.one.one.one`
3. Saving fails with an error about DNS needing to be numeric

**Expected behavior**
Non-numeric DNS should be accepted.

**Screenshots**
~If applicable, add screenshots to help explain your problem.~

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Q Beta 5
 - Backend: Go userspace
 - Version 5.1.1

**Additional context**
~Add any other context about the problem here.~

**Comment by MSF-Jarvis** [comment]
So the latest WireGuard app build from the Play Store doesn't accept non-numeric addresses either (and doesn't collapse keyboard on exiting the fragment :stuck_out_tongue_winking_eye:). Might be worth considering in the future but most definitely not a bug.

**Comment by msfjarvis** [comment]
Hostnames are valid again with https://github.com/msfjarvis/viscerion/commit/f9b774648d2877112ba797cff05bf8afdb704dcd
