### ISSUE TITLE
[Feature request] Handle AFWall+ startup leak block

### ISSUE THREAD

**Issue by MegaArthur** [msfjarvis/viscerion#156]
The most popular firewall for rooted Android devices has a feature that allows a user to block all network traffic through an init.d script before AFWall+ itself can start and apply rules, this prevents unauthorized apps' access to the Internet on startup.

Unfortunately, when WireGuard and Viscerion (with the kernel module) try to bring up last active tunnels at boot while network traffic is blocked, it will fail silently and stay not connected. 

Viscerion could check iptables for a global DROP chain if AFWall+ is detected and enter a wait loop until the condition is resolved through AFWall+ applying rules a few seconds after BOOT_COMPLETED.

**Comment by msfjarvis** [comment]
What does the DROP chain look like? I have never used AFWall+ so I am not really aware of what it's doing.

**Comment by MegaArthur** [comment]
https://bin.privacytools.io/?419bee715e463d9a#+3FsHrk4ZEl3+eldPpLfnILtpjjpwdd15X/sAdjw8QA=

This is the script that executes at boot and sets the iptables DROP chains

**Comment by msfjarvis** [comment]
Thanks, that's immensely helpful. I'm currently dedicating my time to a [different OSS project](https://github.com/zeapo/Android-Password-Store) I'm maintaining but I'll get back to this in a few days.
