### ISSUE TITLE
Hostnames Are Now Not Valid For Endpoints?

### ISSUE THREAD

**Issue by dcplaya** [msfjarvis/viscerion#164]
Seems like a recent update has now made my VPN worthless on my phone because a hostname isn't a valid endpoint. I know there are security implications but I have no other way to connect back to my home since I do not have a static IP.

**Comment by msfjarvis** [comment]
Duplicate of #151

**Comment by dcplaya** [comment]
How is this a duplicate? The other bug report is for DNS, this is for endpoints

**Comment by msfjarvis** [comment]
The same validation applies to both fields, so it's easier to index and triage for me in this fashion. Sorry for not explaining that when I closed the issue.

**Comment by dcplaya** [comment]
Gotcha, that makes sense. Thank you for coming back and explaining!  Great app, love the Tasker integration!
