### ISSUE TITLE
[BUG] Kernel Module not installed

### ISSUE THREAD

**Issue by HyknuF** [msfjarvis/viscerion#165]
**Describe the bug**
Viscerion installed, Root granted (latest Magisk), but no kernel module or something is installed. No setting visible to use kernel module instead of userspace.

**To Reproduce**
1. Magisk installed
2. Root granted
3. No module installed or setting for kernel kodule visible

**Expected behavior**
To use the kernel-module for low battery draining.
(Official WG-Client ~70% of battery load a day)

**Device information (please complete the following information):**
 - Device: OP6
 - OS: Lineage 16
 - Backend:  go userspace, kernel module not visible or installed
 - Version: latest, 5.1.1

Thanks for advice!
Kind regards

**Comment by msfjarvis** [comment]
As the error says, you do need to install the module with a custom kernel.

**Comment by nathanchance** [comment]
The app does not provide or load the kernel module; the kernel itself needs to have that built in. If you are using the stock Lineage kernel, I can guarantee that you do not have that. You need to either build the kernel yourself with WireGuard support or install a custom kernel that does.

**Comment by HyknuF** [comment]
Thanks for quick reply. i see.. thought it would be easy to get a WG kernel module running 😃 I'll try though. 👍🏻

**Comment by msfjarvis** [comment]
Closing as invalid, it appears we're done here. You can e-mail me later or join the [Telegram chat](https://t.me/joinchat/DKHRHEvMR2kz7IW3LB46dQ) if you require assistance in finding or building a kernel.
