### ISSUE TITLE
Prepare for F-Droid builds

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/viscerion#175]
While I personally have absolutely no interest in this ordeal, people have been requesting F-Droid builds for a while so I'm putting this up for Hacktoberfest participants to take a shot at. If this isn't resolved by the time Hacktoberfest 2019 concludes I will close the issue and not reconsider this for the foreseeable future.

**Comment by Skrilltrax** [comment]
Up for grab ?

**Comment by msfjarvis** [comment]
> Up for grab ?

Yessir

**Comment by AniketSK** [comment]
@Skrilltrax how's it going?

**Comment by Skrilltrax** [comment]
@AniketSK I'm not entirely sure what's the procedure for this. I thought it was just adding a product flavor. Would you like to work on it ? I'll just follow along.
