### ISSUE TITLE
Prepare for Android 10's edge-to-edge recommendations

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/viscerion#183]
Checklist

- [x] Draw a transparent navigation bar
- [ ] Ensure FAB draws above system bars
- [ ] Ensure app content does not go under toolbar
- [ ] Ensure the last item of the RV does not go under the FAB or system bars

Branch [msf/edge-to-edge](https://github.com/msfjarvis/viscerion/tree/msf/edge-to-edge) has a work-in-progress implementation that people are more than welcome to pick up and continue from.

**Comment by Skrilltrax** [comment]
Will do

**Comment by Skrilltrax** [comment]
Did 2nd and 3rd, 4th does not go under system bars but fab still covers the switch
