### ISSUE TITLE
[FEATURE] Automatic connection

### ISSUE THREAD

**Issue by proletarius101** [msfjarvis/viscerion#210]
**Is your feature request related to a problem? Please describe.**
I need to connect through Wireguard all the time, but currently it doesn't support auto connection.

**Describe the solution you'd like**
Android has built-in always-on VPN feature to automatically raise up the VPN app when system boots. It also supports blocking traffic not going through that VPN. Vicerion could simply connect to a "default" VPN profile when system requires. By far, Vicerion doesn't support setting a default profile nor connect to the last profile when enabling always-on VPN.

**Describe alternatives you've considered**

**Additional context**

**Comment by msfjarvis** [comment]
If you select `Restore on boot` in the settings menu, Viscerion will attempt to bring up the tunnel that was active when you shut down your device.

**Comment by proletarius101** [comment]
Sorry, but I can't find that option. I do see related code in the codebase.
![img_eggsif_8857308278588859092](https://user-images.githubusercontent.com/54175165/71262291-4e9b3c00-237a-11ea-8a36-680cf6228338.png)

Maybe I looked at a wrong place?

**Comment by msfjarvis** [comment]
Oh I suppose you're using the userspace backend then. It's tricky to bring that back on boot because it may require user confirmation which is difficult to do reliably with an on boot receiver.
