### ISSUE TITLE
[BUG] 5.2.8 - No notification icon

### ISSUE THREAD

**Issue by tend2bend** [msfjarvis/viscerion#226]
**Describe the bug**
No notification icon

**To Reproduce**
1. Open app
2. Connect to VPN

**Expected behavior**
Notification icon should be visible

**Device information (please complete the following information):**
 - Device: Pocophone F1
 - OS: Stock ROM MIUI 11.0.5, Android 9

**Additional context**
I have tried reinstall, restart the device, changed app notification settings, changed notifications priority and locked the app in memory ... without succes.

**Comment by msfjarvis** [comment]
You've removed the backend field from the device information section, I'll need to know that please.

**Comment by tend2bend** [comment]
I'm a noob my friend, sorry. Please explain me how can I provide that info you need.
I have no idea what backend field is.

**Comment by msfjarvis** [comment]
> I'm a noob my friend, sorry. Please explain me how can I provide that info you need.
> I have no idea what backend field is.

Just open settings and take a screenshot of it.

**Comment by tend2bend** [comment]
> 
> 
> > I'm a noob my friend, sorry. Please explain me how can I provide that info you need.
> > I have no idea what backend field is.
> 
> Just open settings and take a screenshot of it.

![Screenshot_2020-01-16-22-19-17-643_me msfjarvis viscerion](https://user-images.githubusercontent.com/59977540/72559934-a14f1180-38ae-11ea-8944-5d5dc4babbd7.jpg)

**Comment by msfjarvis** [comment]
The app does not handle showing icons for the rootless version because that's the OS' responsibility. It's usually like a key and will show up in the statusbar. Here's what it looks like on my Samsung and my Pixel

![Samsung](https://user-images.githubusercontent.com/13348378/72561329-fa2ea200-38ce-11ea-83d5-86b99e33de43.png)

![Pixel](https://user-images.githubusercontent.com/13348378/72561463-4b3e9600-38cf-11ea-9705-6e16c249533d.png)

**Comment by tend2bend** [comment]
I confirm the "VPN" icon, in my case, it appears when I'm connected.

![IMG_20200116_224952](https://user-images.githubusercontent.com/59977540/72561850-c3e32980-38b2-11ea-866c-db3c1cb4b4fc.jpg)

OT: When I am connected on Work Mode as well, that is when the app notification would've come in handy, as I can see I'm connected on both Work Mode and Default user. So no bug here, more like a feature request if it is possible to do that. Thank you.

**Comment by msfjarvis** [comment]
> I confirm the "VPN" icon, in my case, it appears when I'm connected.
> 
> ![IMG_20200116_224952](https://user-images.githubusercontent.com/59977540/72561850-c3e32980-38b2-11ea-866c-db3c1cb4b4fc.jpg)
> 
> OT: When I am connected on Work Mode as well, that is when the app notification would've come in handy, as I can see I'm connected on both Work Mode and Default user. So no bug here, more like a feature request if it is possible to do that. Thank you.

I'm sorry but that's unlikely to come to Viscerion.

**Comment by tend2bend** [comment]
Understood :) Thank you!
