### ISSUE TITLE
[Bug] Biometric authentication can be bypassed

### ISSUE THREAD

**Issue by Atrate** [msfjarvis/viscerion#230]
I have been able to reproducibly bypass Viscerion's biometric authentication by just tapping on an empty area (anywhere except the auth dialog)

**Comment by msfjarvis** [comment]
On version 5.2.9?

**Comment by Atrate** [comment]
Yes.

Device info: LG G6 on Android Q, rooted, Viscerion integrated into /system/priv-app

**Comment by LilligantMatsuri** [comment]
This issue can be reproduced on v5.2.9. Just launch the app and tap any area apart from the auth dialog box, then the bio-auth can be skipped. While the switch in settings works correctly. I can't toggle on/off the bio-auth in this way.

> Device: Redmi Note 7
> OS: MIUI 10 [Android P] (rooted by Magisk)

**Comment by msfjarvis** [comment]
I cannot reproduce this on master so I assume my code cleanup fixed it properly. I'll deploy a new version over the weekend.

**Comment by Atrate** [comment]
Another bug: very quickly double tapping the biometric switch in the settings and then dismissing the prompt can disable biometric auth completely

**Comment by msfjarvis** [comment]
> Another bug: very quickly double tapping the biometric switch in the settings and then dismissing the prompt can disable biometric auth completely

Can you record a video of this?

**Comment by Atrate** [comment]
Now it's fixed, still want a video from the old version?

**Comment by msfjarvis** [comment]
> Now it's fixed, still want a video from the old version?

Nope, thanks for the report.
