### ISSUE TITLE
Alternate config stores?

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/viscerion#66]
The [ConfigStore](https://github.com/MSF-Jarvis/wireguard-kt/blob/master/app/src/main/java/com/wireguard/android/configStore/ConfigStore.kt) interface leaves room for more implementations than just [FileConfigStore](https://github.com/MSF-Jarvis/wireguard-kt/blob/master/app/src/main/java/com/wireguard/android/configStore/FileConfigStore.kt). I firmly believe this can be leveraged to provide a `DatabaseConfigStore` which can then be provided as a backup target to Google's backup service, allowing users to have their tunnels back right when they install the app from the Play Store (working towards that), without having to import them back from a previous export.

**Comment by kdrag0n** [comment]
I'd suggest using Google's Room library. It's a solid abstraction over SQLite3 and manages Java objects via DAOs instead of direct database queries. https://developer.android.com/training/data-storage/room/

**Comment by MSF-Jarvis** [comment]
> I'd suggest using Google's Room library. It's a solid abstraction over SQLite3 and manages Java objects via DAOs instead of direct database queries. [developer.android.com/training/data-storage/room](https://developer.android.com/training/data-storage/room/)

That's the plan
